# Generated by Django 5.1.3 on 2024-11-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('year_founded', models.IntegerField()),
                ('industry', models.CharField(max_length=255)),
                ('size_range', models.IntegerField()),
                ('locality', models.CharField(max_length=255)),
                ('country_linkedin_url', models.URLField()),
                ('current_employee_estimate', models.IntegerField()),
                ('total_employee_estimate', models.IntegerField()),
            ],
        ),
    ]
